# Generated by Django 6.0.4 on 2026-04-10 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("EXPORT", "Export"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("FAILED_LOGIN", "Failed Login"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("DATA_ACCESS", "Data Access"),
                            ("SYSTEM_CHANGE", "System Change"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("reason", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("BULK_INSERT", "Bulk Insert"),
                            ("BULK_UPDATE", "Bulk Update"),
                            ("BULK_DELETE", "Bulk Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("record_id", models.CharField(max_length=100)),
                ("old_data", models.JSONField(blank=True, default=dict)),
                ("new_data", models.JSONField(blank=True, default=dict)),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Data Change Log",
                "verbose_name_plural": "Data Change Logs",
                "db_table": "data_change_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "exception_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                (
                    "function_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "db_table": "error_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("response_time_ms", models.IntegerField()),
                ("status_code", models.IntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("request_size", models.IntegerField(blank=True, null=True)),
                ("response_size", models.IntegerField(blank=True, null=True)),
                ("query_count", models.IntegerField(blank=True, null=True)),
                ("query_time_ms", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Performance Log",
                "verbose_name_plural": "Performance Logs",
                "db_table": "performance_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FAILED_LOGIN", "Failed Login"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("BRUTE_FORCE_ATTEMPT", "Brute Force Attempt"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("DATA_BREACH_ATTEMPT", "Data Breach Attempt"),
                            ("MALICIOUS_REQUEST", "Malicious Request"),
                            ("RATE_LIMIT_EXCEEDED", "Rate Limit Exceeded"),
                            ("SESSION_HIJACK", "Session Hijack"),
                            ("ACCOUNT_LOCKOUT", "Account Lockout"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("TWO_FACTOR_AUTH", "Two Factor Auth"),
                            ("API_KEY_USAGE", "API Key Usage"),
                            ("ADMIN_ACCESS", "Admin Access"),
                            ("SECURITY_POLICY_VIOLATION", "Security Policy Violation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("geo_location", models.JSONField(blank=True, default=dict)),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Security Log",
                "verbose_name_plural": "Security Logs",
                "db_table": "security_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("TRANSACTION_COMPLETED", "Transaction Completed"),
                            ("TRANSACTION_FAILED", "Transaction Failed"),
                            ("CONTACT_FORM_SUBMIT", "Contact Form Submit"),
                            ("INSTITUTIONAL_APPLICATION", "Institutional Application"),
                            ("MAGIC_LINK_SENT", "Magic Link Sent"),
                            ("MAGIC_LINK_USED", "Magic Link Used"),
                            ("ACCOUNT_CREATED", "Account Created"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("DEPOSIT_PROCESSED", "Deposit Processed"),
                            ("WITHDRAWAL_PROCESSED", "Withdrawal Processed"),
                            ("PORTFOLIO_UPDATED", "Portfolio Updated"),
                            ("ADMIN_ACTION", "Admin Action"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("API_ACCESS", "API Access"),
                            ("DATA_EXPORT", "Data Export"),
                            ("SYSTEM_ERROR", "System Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "System Log",
                "verbose_name_plural": "System Logs",
                "db_table": "system_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
