# Generated by Django 6.0.4 on 2026-04-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Logs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datachangelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_change_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_errors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="error_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performance_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securitylog",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_security_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "timestamp"], name="audit_logs_event_t_222f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "timestamp"],
                name="audit_logs_resourc_4f6f11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datachangelog",
            index=models.Index(
                fields=["table_name", "timestamp"],
                name="data_change_table_n_6c39ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datachangelog",
            index=models.Index(
                fields=["action", "timestamp"], name="data_change_action_ab78ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datachangelog",
            index=models.Index(
                fields=["user", "timestamp"], name="data_change_user_id_06d9d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datachangelog",
            index=models.Index(
                fields=["timestamp"], name="data_change_timesta_ac106c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["level", "timestamp"], name="error_logs_level_2c036d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["user", "timestamp"], name="error_logs_user_id_f596a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["resolved", "timestamp"], name="error_logs_resolve_13f8e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["timestamp"], name="error_logs_timesta_673a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancelog",
            index=models.Index(
                fields=["endpoint", "timestamp"], name="performance_endpoin_87892d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancelog",
            index=models.Index(
                fields=["method", "timestamp"], name="performance_method_4aabef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancelog",
            index=models.Index(
                fields=["status_code", "timestamp"],
                name="performance_status__157caa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancelog",
            index=models.Index(
                fields=["response_time_ms"], name="performance_respons_d21d73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancelog",
            index=models.Index(
                fields=["timestamp"], name="performance_timesta_4534d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["user", "timestamp"], name="security_lo_user_id_c113a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["event_type", "timestamp"],
                name="security_lo_event_t_9e8783_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["severity", "timestamp"], name="security_lo_severit_4109e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="security_lo_ip_addr_0efe7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["timestamp"], name="security_lo_timesta_c6c01c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["user", "timestamp"], name="system_logs_user_id_942324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["action", "timestamp"], name="system_logs_action_c9bfcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["severity", "timestamp"], name="system_logs_severit_e4003b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["timestamp"], name="system_logs_timesta_84e60c_idx"
            ),
        ),
    ]
